### ISSUE TITLE
Unable to add option with 0x0 value

### ISSUE THREAD

**Issue by Sibyx** [filipskrabak/protocol-designer#3]
When adding a new protocol field It's currently impossible to add zero (0x0) as value for the field (check screenshot bellow).

![Screenshot 2024-05-28 at 15-58-21 Protocol Designer](https://github.com/filipskrabak/protocol-designer/assets/2022531/2503cc45-c060-437e-b858-2115caf6f116)

I am using Firefox 126 on macOS 14.5 (23F79).

I have also noticed that the form field is type of `number`. This is not very practical because you usually have to define these values in hexa (`0x01`) or binary (`0001b`). It will be nice to support these formats.

**Comment by filipskrabak** [comment]
Fixed in f2f0bcc

Thanks for the report :)
